<div class="modal" id="modal-upload-townplanning" role="dialog" data-keyboard="false" data-backdrop="static" style="z-index: 99999;" >
    <div class="modal-dialog modal-sm ">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" style="font-size: 15px">
                <h3 class="modal-title">Upload Town Planning</h3>
                <button type="button" class="close btn-sm btn-close-detail" data-dismiss="modal">&times;</button>

            </div>
            <form method="post" enctype="multipart/form-data" id="form-upload-townplanning">
            <div class="modal-body kotak_modal_body">
                <div class="mellong">
                    <div class="container my-container" style="height: auto; overflow: hidden;" >
                        
                                Pilih File: 
                                <input name="filetownplanning" style="margin-top: 10px; margin-bottom: 10px;" type="file" required="required"> 
                                
                                <div class="checkbox">
                                  <label><input type="checkbox" name="overwrite" value="1"> Overwrite</label>
                                </div>
                                <!--<input name="upload" type="submit" value="Import">-->
                                <a href="app/erems/uploads/msexcel/upload_unit.xlsx" target="blank"> Download Template </a>
                        
                    </div> 
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary btn-sm" >Import</button>
                <button type="button" class="btn btn-danger btn-sm btn-close-detail" data-dismiss="modal">Close</button>
            </div>
            </form>
        </div>

    </div>
</div>

        