<html>
	<head>
		<title><?php echo $this->apps_title,' - ',$this->apps_company;?></title>
		<meta charset="utf-8">		
		<meta http-equiv="Pragma" content="no-cache" />
		<meta http-equiv="Cache-Control" content="no-store, no-cache, must-revalidate, post-check=0, pre-check=0" />
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8;" />
		<meta http-equiv="imagetoolbar" content="no">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="robots" content="noindex, nofollow" />		
		<meta name="http_equiv" content="text/html; charset=utf-8;" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />		
		<link rel="icon" type="image/x-icon" href="app/main/images/icons/Ciputra.ico" />
		<link rel="shortcut icon" type="image/x-icon" href="app/main/images/icons/Ciputra.ico" />
		<link rel="stylesheet" type="text/css" href="app/main/js-css/style.mobile.css" />
	</head>
	<body>
	</body>
</html>