<div id="logintitle" class="front-title" style="margin-bottom:20px;padding-bottom:10px;padding-left:3px;">Password Reset</div>
<p style="text-align:left;"><b>How do you want to reset your password?</b><br/><br/>
We found the following information associated with your account.
</p>
<form name="frmsearch" id="frmsearch">
        <input type="hidden" name="mode" value="sendemail" />
	<table cellspacing="0" cellpadding="3" align="center" border="0">
                <?php foreach($this->email_list as $row){?>
                <tr>
			
                    <td><input type="radio" name="nomor" value="<?php echo $row["nomor"]; ?>" checked /><?php echo $row["teks"]; ?></td>
		</tr>
                <?php } ?>
		
		<tr>
			<td colspan="2" style="padding-top:20px;">
                                 <span class="link small" id="lnkback" style="margin-top:10px;float:left">Back to Login Form</span>
				<input type="button" value="Continue" name="btnContinue" id="btnContinue" style="width:80px;height:30px;font-size:0.9em;float:right;" />				
			</td>
		</tr>
	</table>
</form>
<script type="text/javascript">
    $('#btnContinue').click(function(){  
        //loadBasePage({actionName:'searchuserces', method:'POST', data:'#frmsearch'}); 
        loadBasePage({actionName:'forgetpassword',method:'POST', data:'#frmsearch'});
    });
    $('#lnkback').click(function(){  
        loadBasePage({actionName:'login'});
    });
</script>