<div id="logintitle" class="front-title" style="margin-bottom:20px;padding-bottom:10px;padding-left:3px;">We just emailed you a link</div>
<p style="text-align:left;">Please check your email and click the secure link.</p>
<p style="text-align:left;"><?php echo $this->pesan;?>.</p>

<p>If you don’t see our email, check your spam folder</p>



<form name="frmsearch" id="frmsearch">
	<table cellspacing="0" cellpadding="3" align="center" border="0">
             
                <input type="hidden" name="nomor" value="<?php echo $this->nomor ?>" />
                <input type="hidden" name="mode" value="sendemail" />
                <input type="hidden" name="tipe_request" value="resend" />
		
		<tr>
			<td colspan="2" style="padding-top:20px;">
                                 <span class="link small" id="lnkback" style="margin-top:10px;float:left">Back to Login Form</span>
                                 
                            

						
			</td>
		</tr>
	</table>
</form>
<script type="text/javascript">
    $('#btnResend').click(function(){  
        //loadBasePage({actionName:'searchuserces', method:'POST', data:'#frmsearch'}); 
       loadBasePage({actionName:'forgetpassword',method:'POST', data:'#frmsearch'});
    });
    $('#lnkback').click(function(){  
        loadBasePage({actionName:'login'});
    });
</script>