<div id="logintitle" class="front-title" style="margin-bottom:20px;padding-bottom:10px;padding-left:3px;">Forgot Password</div>
<?php if(isset($this->pesan)) {?>
    <p style="color:red;text-align: left;"><?php echo $this->pesan; ?></p>
<?php } ?>

<form name="frmsearch" id="frmsearch">
	<table cellspacing="0" cellpadding="3" align="center" border="0">
                <tr>
			
			<td>Enter your email or username.</td>
		</tr>
		<tr>
			<input type="hidden" name="mode" value="searchuser" size="35" />
			<td><input type="text" name="searchkey" id="usr" value="<?php echo $this->searchkey ?>" size="35" /></td>
		</tr>
		
		<tr>
			<td colspan="2" style="padding-top:20px;">
                            <span class="link small" id="lnkback" style="margin-top:10px;float:left">Back to Login Form</span>
				<input type="submit" value="Search" name="btnSearch" id="btnsearch" style="width:80px;height:30px;font-size:0.9em;float:right;" />				
			</td>
		</tr>
	</table>
</form>
<script type="text/javascript">
    $('#btnsearch').click(function(){  
        //loadBasePage({actionName:'searchuserces', method:'POST', data:'#frmsearch'}); 
        loadBasePage({actionName:'forgetpassword',method:'POST', data:'#frmsearch'});
    });
    $('#lnkback').click(function(){  
        loadBasePage({actionName:'login'});
    });
</script>