<div style="font-size:11px;line-height:1.7em;">
	<div style="margin:10 10 30 10;padding:0;font-weight:bold;font-size:16px;">
		Terms of Service
	</div>
	<div style="font-weight:bold;padding:10px;background:#fdffbe;margin-bottom:30px;">
		Hereby, I declare have already read and agree to follow all the Terms of Service before using this system.
	</div>
	<ol style="margin-left:0px;padding-left:25px;">
		<li>
			<b>ACCEPTANCE OF TERMS</b>
			<div style="padding:5 0 50 0;">
				Ciputra Group provides this service only to authorized users, subject to the following Terms of Service ("TOS"), 
				which may be updated by Ciputra Group from time to time without notice to users. 
			</div>
		</li>
		<li>
			<b>DESCRIPTION OF SERVICE</b>
			<div style="padding:5 0 50 0;">
				.....
			</div>
		</li>
		<li>
			<b>REGISTRATION OBLIGATIONS</b>
			<div style="padding:5 0 50 0;">
				.....
			</div>
		</li>
		<li>
			<b>PERSONAL PASSWORD AND SECURITY</b>
			<div style="padding:5 0 50 0;">
				User will receive a password and account designation upon completing the system installment. 
				User is responsible for maintaining the confidentiality of the password and account, and are fully responsible 
				for all activities that occur under user's personal password or account. 
				User agree to immediately notify Ciputra Group of any unauthorized use of password or account.
			</div>
		</li>
		<li>
			<b>NO RESALE OF SERVICE</b>
			<div style="padding:5 0 50 0;">
				Users agrees not to reproduce, duplicate, copy, sell, trade, resale or exploit for any commercial purposes, 
				any portion of the system (including any password and I.D.).
			</div>
		</li>
		<li>
			<b>MODIFICATIONS TO SYSTEM</b>
			<div style="padding:5 0 50 0;">
				Ciputra Group reserves the right at any time and from time to time to modify the System (or any part thereof) 
				with or without notice.
			</div>
		</li>
		<li>
			<b>VIOLATIONS</b>
			<div style="padding:5 0 50 0;">
				Please report any violations of the TOS to Ciputra Group.
			</div>
		</li>
		<li>
			<b>VALIDITY OF DATA</b>
			<div style="padding:5 0 50 0;">
				.....
			</div>
		</li>
	</ol>
	<div class="small" style="padding:1px;background:#fdffbe;margin-bottom:10px;">
		&nbsp;
	</div>
</div>