<html>
    <head>
        <title><?php echo $this->apps_title, ' - ', $this->apps_company; ?></title>
        <meta http-equiv="Pragma" content="no-cache" />
        <meta http-equiv="Cache-Control" content="no-store, no-cache, must-revalidate, post-check=0, pre-check=0" />
        <meta name="robots" content="noindex,nofollow" />
        <meta name="http_equiv" content="text/html; charset=utf-8;" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8;" />
        <meta http-equiv="imagetoolbar" content="no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="baseUrl" content="<?php echo $this->appBaseUrl; ?>" />
        <link rel="icon" type="image/x-icon" href="<?php echo $this->baseUrl(); ?>/app/main/images/icons/Ciputra.ico" />
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->baseUrl(); ?>/app/main/images/icons/Ciputra.ico" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/app/main/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/app/main/bootstrap/css/datepicker.css" />

<!--<<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/resources/jquery-ui-1.12.1/jquery-ui.min.css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/resources/jquery-ui-1.12.1/jquery-ui.structure.min.css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/resources/jquery-ui-1.12.1/jquery-ui.theme.min.css" />-->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/app/main/js-css/style.css" /><?php if (!$this->validuseragent): ?>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/resources/jquery-toastmessage/jquery.toastmessage.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/app/main/js-css/aplijs-style.css" />
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/resources/jquery/jquery.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/resources/jquery/jquery.cookie.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/resources/jquery-toastmessage/jquery.toastmessage.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/resources/jquery-ui-1.12.1/jquery-ui.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/app/main/bootstrap/js/popper.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/app/main/bootstrap/js/bootstrap.min.js"></script>    
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/app/main/bootstrap/js/datepicker.min.js"></script>

        <?php endif; ?></head>
    <body>
        <div id="wrapper">
            <table id="wrapper-front">
                <tr><td id="wrapper-front-header"></td></tr>
                <tr><td id="wrapper-front-content">
                        <table id="front-content-wrapper">
                            <tr>
                                <td id="front-content">
                                    <!--start -->
                                    <div id="logintitle" class="front-title" style="margin-bottom:20px;padding-bottom:10px;padding-left:3px;">Finally, choose a new password</div>
                                    <p style="text-align:left;">Password must include at least 8 characters including at least 1 number and 1 alphabet.</p>
                                    <p style="text-align:left;color:red;" id="up_pesan">&nbsp;</p>

                                    <form name="frmupdatepass" id="frmupdatepass">
                                        <input type="hidden" name="key" value="<?php echo $this->form_key ?>" />
                                        <input type="hidden" name="m" value="<?php echo $this->m ?>" />
                                        <input type="hidden" name="code" value="<?php echo $this->code ?>" />
                                        <input type="hidden" name="i" value="<?php echo $this->i ?>" />
                                        <table cellspacing="0" cellpadding="3" align="left" border="0">


                                            <tr>
                                                <td>New Password * <input type="password" name="password1" id="password1" value="" size="35" /></td>
                                            </tr>
                                            <tr>
                                                <td>Retype new Password *<input type="password" name="password2" id="password2" value="" size="35" /></td>
                                            </tr>

                                            <tr>
                                                <td colspan="2" style="padding-top:20px;">
                                                    <span class="link small" id="lnkback" style="margin-top:10px;float:left">Back to Login Form</span>
                                                    <input type="button" value="Submit" name="btnSubmit" id="btnSubmit" style="width:80px;height:30px;font-size:0.9em;float:right;" />				
                                                </td>
                                            </tr>
                                        </table>
                                    </form>
                                    <!-- end -->
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td id="wrapper-front-footer">
                        <div><?php echo $this->apps_version, '<br />', $this->apps_copyright; ?>
                        </div><?php if (!$this->isChrome): ?>
                            <div id="browser-info">
                                <?php
                                echo '<strong>' . $this->globalparam['value'] . '</strong>';
                                ?>
                                <br/>
                                <br/>
                                <img src="<?php echo $this->baseUrl(); ?>/app/main/images/icons/chrome.gif" title="Google Chrome" alt="Google Chrome" id="browser-icon" align="absmiddle" /> Google Chrome is the most recommended browser. Get the latest version <span class="link" onclick="window.open('https://www.google.com/intl/en/chrome/')"><u>here</u></span>.</div><?php endif; ?></td></tr></table><div id="content"></div></div><div id="wrapper-mask"></div><div id="cookie-info">
            <div class="info info-error">
                Your browser's cookie functionality is turned off. Please turn it on and reload the page !
            </div>
            <script src="<?php echo $this->baseUrl(); ?>/app/main/bootstrap/js/popper.min.js"></script>               
            <script src="<?php echo $this->baseUrl(); ?>/app/main/bootstrap/js/bootstrap.min.js"></script>


        </div>

        <script type="text/javascript">
                                    $('#btnSubmit').click(function () {

                                        var checkPassword = function (password) {
                                            return !!password.match(/^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/);
                                        };

                                        var pass1 = $('#password1').val();
                                        var pass2 = $('#password2').val();
                                        var pesan = "";
                                        if (!checkPassword(pass1)) {
                                            pesan = "Password must be 8 characters and contain 1 number and 1 alphabet";

                                        } else {
                                            if (pass1 !== pass2) {
                                                pesan = "Password didnt match.";
                                            } else {
                                                $.ajax({
                                                    type: "POST",
                                                    url: "<?php echo $this->form_url ?>",
                                                    data: {
                                                        m: $('#frmupdatepass').find('input[name="m"]').val(),
                                                        code: $('#frmupdatepass').find('input[name="code"]').val(),
                                                        i: $('#frmupdatepass').find('input[name="i"]').val(),
                                                        p: $('#frmupdatepass').find('input[name="password1"]').val(),
                                                        key: $('#frmupdatepass').find('input[name="key"]').val()
                                                    },
                                                    success: function (response) {
                                                        var obj = JSON.parse(response);
                                                      //  console.log(obj);
                                                        
                                                        if(!obj.status){
                                                            $('#up_pesan').text(obj.message);
                                                        }else{
                                                           // $('#up_pesan').text(obj.message);
                                                           $('#front-content').html("<p><b>Yeaahh!!</b></p><p>Password successfully updated. Please login using a new password.</p><p><span class='link small' id='lnkback2' style='margin-top:10px;' onclick='window.location.href = \"<?php echo $this->url ?>\"'>Back to Login Form</span></p>");
                                                        }
                                                    }
                                                });
                                            }

                                        }
                                        $('#up_pesan').text(pesan);

                                    });
                                    $('#lnkback').click(function () {
                                        window.location.href = "<?php echo $this->url ?>";
                                    });
                                   
        </script>                         

    </body>
</html>