<style type="text/css">
	.table-stock td {
		text-align: center;
                background-color: red;
	}
	.table-stock{
		border: 4px solid black;
	}
        .table-stock tr{
		border: 4px solid black;
	}
        .table-stock td{
		border: 4px solid black;
	}
        .table-stock th {
                text-align: center;
                background-color: gray;
                border: 4px solid black;
        }
        .btn-copy-clipboard{
            margin-bottom: 10px;
            background-color: #28a745;
        }
</style>
<div class="mellong container-fluid">
        <form id="formtablestock">

            <input type="hidden" name="formorderajb_id" id="formorderajb_id">
            <input type="hidden" name="purchaseletter_purchaseletter_id" id="purchaseletter_purchaseletter_id">
            
            <div class="col col-md-12 text-center" style="margin-bottom: 20px"> 
                <i class="fas fa-square" style="font-size:20px;color:red"></i> <span style="margin-right: 10px"><b>: Sold</b> </span> 
                <i class="fas fa-square" style="font-size:20px;color:yellow"></i> <span style="margin-right: 10px"><b>: Sold Under 30%</b> </span>
                <i class="fas fa-square" style="font-size:20px;color:gray"></i> <span style="margin-right: 10px"><b>: Proses Batal</b> </span>
                <i class="fas fa-square" style="font-size:20px;color:orange"></i> <span style="margin-right: 10px"><b>: Hold</b> </span>
                <i class="fas fa-square" style="font-size:20px;color:salmon"></i> <span style="margin-right: 10px"><b>: Broken</b> </span>
                <i class="fas fa-square" style="font-size:20px;color:blue"></i> <span style="margin-right: 10px"><b>: Booked</b> </span>
                <i class="fas fa-square" style="font-size:20px;color:greenyellow"></i> <span style="margin-right: 10px"><b>: Planning</b> </span>
                <i class="fas fa-square" style="font-size:20px;color:green"></i> <span><b>: Available</b> </span>
            </div>
            <button type="button" class="btn btn-success btn-sm btn-copy-clipboard" id="btn-export" >Export Excel</button>
            <!-- <br> -->
            <!-- <div class="d-flex align-items-center">
            <strong>Loading...</strong>
            <div class="spinner-border ml-auto" role="status" aria-hidden="true"></div>
            </div> -->
            <table class = "table table-stock" id = "idtablestock">
                    <tr>
                            <th><b>Lt/No</b></th>
                            <?php
                                $nomor = $this->data['nomor'];
                                $nomor2 = array();
                                
                                foreach ($nomor['data'] as $value){
                                    // array_push($nomor2,$value['nomor']);
                            ?>
                                <th><b><?php echo trim($value['nomor'])  ?></b></th>
                            <?php
                                }
                            ?>
                    </tr>
                    <?php 
                        $block = $this->data['block'];
                        $detail = $this->data['detail'];
                        $detail2 = array();
                        $detail3 = array();

//                        var_dump($block['data']);                        die();
                        foreach ($block['data'] as $value) {
                    ?>
                        <tr>
                            <td style="background-color: whitesmoke;"><b><?php echo $value['blok']; ?></b></td>
                            <?php 
                                foreach ($detail['data'] as $values){
                                    if($value['blok'] == $values['blok']){
                                        // $b = array('cluster_id'=>$values['cluster_id']);
                                        $tes = array(trim($values['nomor']),$values['unit_id'],$values['status'],$values['batal'],$values['persen_payment']);
                                        array_push($detail2, $tes);
                                        array_push($detail3, trim($values['nomor']));
//                                        $detail2=$values['nomor'];
//                                            $detail2[$values['nomor']]=$b;
                                    }
                                }
                                
                            //    var_dump($detail2);
                            //    echo '<br>';
                            //    var_dump($detail3);
                            //    die();
                                
                                foreach ($nomor['data'] as $val) {

                                    if(in_array(trim($val['nomor']), $detail3)){
//                                        var_dump('wew'.$val['nomor']);
                                        foreach ($detail2 as $data){
//                                          var_dump($data);
                                    
                                            if (trim($val['nomor']) == $data[0]) {
                                                if($data[3] == 1){
                            ?>
                                                    <td class="btn-detail" style="background-color: gray;" unit-id="<?php echo $data[1]; ?>"> <a href="" class="btn-detail" unit-id="<?php echo $data[1]; ?>" style="text-decoration: none;color:black; "><b><?php echo $val['nomor']; ?></b></a></td>
                            <?php
                                                } else {
                                                
                                                if($data[2]==5){
                                                    if ($data[4] < 30){
                            ?>
                                                        <td class="btn-detail" style="background-color: yellow;" unit-id="<?php echo $data[1]; ?>"> <a href="" class="btn-detail" unit-id="<?php echo $data[1]; ?>" style="text-decoration: none;color:black; "><b><?php echo $val['nomor']; ?></b></a></td>
                            <?php
                                                    }else {
                            ?>
                                                        <td class="btn-detail" style="background-color: red;" unit-id="<?php echo $data[1]; ?>"> <a href="" class="btn-detail" unit-id="<?php echo $data[1]; ?>" style="text-decoration: none;color:black; "><b><?php echo $val['nomor']; ?></b></a></td>
                            <?php
                                                    }
                                                }
                                                else if($data[2]==11){
                            ?>
                                                    <td class=" btn-detail" style="background-color: orange;" unit-id="<?php echo $data[1]; ?>"><a href="" class="btn-detail" unit-id="<?php echo $data[1]; ?>" style="text-decoration: none;color:black; "><b><?php echo $val['nomor']; ?></b></a></td>
                            <?php
                                                }
                                                else if($data[2]==10) {
                            ?>
                                                    <td class=" btn-detail" style="background-color: salmon;" unit-id="<?php echo $data[1]; ?>"><a href="" class="btn-detail" unit-id="<?php echo $data[1]; ?>" style="text-decoration: none;color:black; "><b><?php echo $val['nomor']; ?></b></a></td>
                            <?php
                                                }
                                                else if($data[2]==4) {
                            ?>
                                                    <td class=" btn-detail" style="background-color: blue;" unit-id="<?php echo $data[1]; ?>"><a href="" class="btn-detail" unit-id="<?php echo $data[1]; ?>" style="text-decoration: none;color:black; "><b><?php echo $val['nomor']; ?></b></a></td>
                            <?php
                                                }
                                                else if($data[2]==1) {
                            ?>
                                                    <td class=" btn-detail" style="background-color: greenyellow;" unit-id="<?php echo $data[1]; ?>"><a href="" class="btn-detail" unit-id="<?php echo $data[1]; ?>" style="text-decoration: none;color:black; "><b><?php echo $val['nomor']; ?></b></a></td>
                            <?php
                                                }
                                                else if($data[2]==3) {
                            ?>
                                                    <td class=" btn-detail" style="background-color: green;" unit-id="<?php echo $data[1]; ?>"><a href="" class="btn-detail" unit-id="<?php echo $data[1]; ?>" style="text-decoration: none;color:black; "><b><?php echo $val['nomor']; ?></b></a></td>
                            <?php
                                                } else {
                                                    ?>
                                                    <td class=" btn-detail" style="background-color: whitesmoke;" unit-id="<?php echo $data[1]; ?>"><a href="" class="btn-detail" unit-id="<?php echo $data[1]; ?>" style="text-decoration: none;color:black; "><b><?php echo $val['nomor']; ?></b></a></td>
                                                <?php
                                                }
                                                }
                                            
                                            }
                                        }
                                    }
                                    else { 
                            ?>
                                            <td style="background-color: whitesmoke;"><b></b></td>
                            <?php
                                        
                                    }
                                    
                                }

                                $detail2 = array();
                                $detail3 = array();
                            }
                            ?>
                        </tr>
                        
                    
            </table>

        </form>
    
        <div class="modal" id="modal-detail" role="dialog" data-keyboard="false" data-backdrop="static" style="z-index: 99999;">
        
        </div>
</div>
